# Generated by Django 2.1.4 on 2019-01-02 01:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('syllabus', models.TextField(null=True)),
                ('section', models.IntegerField(default=1)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=None)),
                ('hour', models.IntegerField(choices=[(0, '9:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00')], default=None)),
                ('to', models.IntegerField(choices=[(0, '9:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00')], default=1)),
                ('credit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depName', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyName', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='empty@mail.com', max_length=254)),
                ('password', models.CharField(max_length=255, null=True)),
                ('usertype', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slotName', models.IntegerField(choices=[(0, 'FREE_I'), (1, 'DEPT_I'), (2, 'COMP_I'), (3, 'MATH101'), (4, 'PHYS101'), (5, 'FREE_II'), (6, 'FREE_III'), (7, 'COMP_II'), (8, 'DEPT_II'), (9, 'FREE_I'), (10, 'FREE_I'), (11, 'EE335'), (12, 'EE225'), (13, 'MATH102'), (14, 'PHYS102'), (14, 'MATH200')], default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Reg.Course')),
                ('major', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Reg.Department')),
                ('slotName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Reg.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNo', models.CharField(default=218, max_length=100, primary_key=True, serialize=False)),
                ('depName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Instructor_Course',
            fields=[
                ('Semester', models.IntegerField(choices=[(0, 'FALL'), (1, 'SPRING')], default=0)),
                ('slotName', models.IntegerField(choices=[(0, 'FREE_I'), (1, 'DEPT_I'), (2, 'COMP_I'), (3, 'MATH101'), (4, 'PHYS101'), (5, 'FREE_II'), (6, 'FREE_III'), (7, 'COMP_II'), (8, 'DEPT_II'), (9, 'FREE_I'), (10, 'FREE_I'), (11, 'EE335'), (12, 'EE225'), (13, 'MATH102'), (14, 'PHYS102'), (14, 'MATH200')], default=0, primary_key=True, serialize=False)),
                ('CourseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Course')),
                ('StudentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canTake', models.IntegerField(default=0)),
                ('slotName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Slot')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Student')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='empty@mail.com', max_length=254)),
                ('password', models.CharField(max_length=255, null=True)),
                ('usertype', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Reg.Register')),
                ('FacName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Reg.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reg.Register'),
        ),
        migrations.AddField(
            model_name='department',
            name='majority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='depName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reg.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='Emine Ekin', on_delete=django.db.models.deletion.CASCADE, to='Reg.Register'),
        ),
        migrations.AlterUniqueTogether(
            name='student_slot',
            unique_together={('studentNo', 'slotName')},
        ),
        migrations.AlterUniqueTogether(
            name='student_instructor_course',
            unique_together={('StudentNo', 'CourseName', 'Semester', 'slotName')},
        ),
        migrations.AlterUniqueTogether(
            name='slot_course',
            unique_together={('major', 'slotName', 'courseName')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('depName', 'majority')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'day', 'hour')},
        ),
    ]
